### ISSUE TITLE
On windows cannot find module

### ISSUE THREAD

**Issue by shnigi** [ahfarmer/minimal-react-starter#2] opened 2017-02-25 14:39 UTC
I get this error on windows machine out of the box

```
ERROR in ./src/main.js
Module build failed: Error: Cannot find module '../modules/web.dom.iterable' (While processing preset: "I:\\Progra
m Files (x86)\\UwAmp\\www\\minimal-react-starter\\node_modules\\babel-preset-latest\\lib\\index.js")
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (I:\Program Files (x86)\UwAmp\www\minimal-react-starter\node_modules\babel-preset-latest
\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-template-literals\node_modules\babel-
runtime\node_modules\core-js\library\fn\get-iterator.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 @ multi ./main.js
webpack: Failed to compile.
```

**Comment by andrewagain** [comment] 2017-03-12 23:27
@shnigi thanks for reporting this! unfortunately i don't have access to a windows machine just yet. 

I found a similar issue reported here: http://www.curtismlarson.com/blog/2016/05/12/webpack-cannot-find-module-web-dom-iterable/

This is the suggested fix:

```
rm -rf node_modules && npm install
```

But I suppose if you just cloned this project and ran `npm install`, you would already have a clean `node_modules` folder?

**Comment by SaraChicaD** [comment] 2017-03-29 22:55
hiya @ahfarmer i have the same issue on mac it's as soon as i add this code that the compile breaks:

`import React from 'react';
import ReactDOM from 'react-dom';
import Counter from './Counter';
 
document.addEventListener('DOMContentLoaded', function() {
  ReactDOM.render(
    React.createElement(Counter),
    document.getElementById('mount')
  );
});`

I get this error:

`npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! my-project@1.0.0 compile: `webpack`
npm ERR! Exit status 2`

**Comment by andrewagain** [comment] 2017-06-23 18:53
@SaraChicaD I know this has been a while - I finally realized that the issue is this repository requires at least npm 3 and you were on npm 2.

I'm going to close the issue - let me know if you come back to this and it's not working for you. Also let me know if you for some reason can't upgrade from npm 2 to the latest stable version (which I think is npm 3 right now).

**Closed as completed by andrewagain** 2017-06-23 18:53 UTC
